/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteRouteImport } from './routes/_admin/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminClientsRouteImport } from './routes/_admin/clients'
import { Route as AdminItemsRouteImport } from './routes/_admin/items'
import { Route as AdminPaymentsRouteImport } from './routes/_admin/payments'
import { Route as AdminRequestsRouteImport } from './routes/_admin/requests'
import { Route as AdminUsersRouteImport } from './routes/_admin/users'
import { Route as InvoicesPaymentIdPrintRouteImport } from './routes/invoices/$paymentId/print'
import { Route as RequestsRequestIdPrintRouteImport } from './routes/requests/$requestId/print'

const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminItemsRoute = AdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRequestsRoute = AdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRouteRoute,
} as any)
const InvoicesPaymentIdPrintRoute = InvoicesPaymentIdPrintRouteImport.update({
  id: '/invoices/$paymentId/print',
  path: '/invoices/$paymentId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdPrintRoute = RequestsRequestIdPrintRouteImport.update({
  id: '/requests/$requestId/print',
  path: '/requests/$requestId/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/clients': typeof AdminClientsRoute
  '/items': typeof AdminItemsRoute
  '/payments': typeof AdminPaymentsRoute
  '/requests': typeof AdminRequestsRoute
  '/users': typeof AdminUsersRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/clients': typeof AdminClientsRoute
  '/items': typeof AdminItemsRoute
  '/payments': typeof AdminPaymentsRoute
  '/requests': typeof AdminRequestsRoute
  '/users': typeof AdminUsersRoute
  '/': typeof AdminIndexRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/clients': typeof AdminClientsRoute
  '/_admin/items': typeof AdminItemsRoute
  '/_admin/payments': typeof AdminPaymentsRoute
  '/_admin/requests': typeof AdminRequestsRoute
  '/_admin/users': typeof AdminUsersRoute
  '/_admin/': typeof AdminIndexRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/clients'
    | '/items'
    | '/payments'
    | '/requests'
    | '/users'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/clients'
    | '/items'
    | '/payments'
    | '/requests'
    | '/users'
    | '/'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/clients'
    | '/_admin/items'
    | '/_admin/payments'
    | '/_admin/requests'
    | '/_admin/users'
    | '/_admin/'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  InvoicesPaymentIdPrintRoute: typeof InvoicesPaymentIdPrintRoute
  RequestsRequestIdPrintRoute: typeof RequestsRequestIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/clients': {
      id: '/_admin/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/items': {
      id: '/_admin/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AdminItemsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/payments': {
      id: '/_admin/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/requests': {
      id: '/_admin/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AdminRequestsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_admin/users': {
      id: '/_admin/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/invoices/$paymentId/print': {
      id: '/invoices/$paymentId/print'
      path: '/invoices/$paymentId/print'
      fullPath: '/invoices/$paymentId/print'
      preLoaderRoute: typeof InvoicesPaymentIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId/print': {
      id: '/requests/$requestId/print'
      path: '/requests/$requestId/print'
      fullPath: '/requests/$requestId/print'
      preLoaderRoute: typeof RequestsRequestIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteRouteChildren {
  AdminClientsRoute: typeof AdminClientsRoute
  AdminItemsRoute: typeof AdminItemsRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminRequestsRoute: typeof AdminRequestsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminClientsRoute: AdminClientsRoute,
  AdminItemsRoute: AdminItemsRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminRequestsRoute: AdminRequestsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  InvoicesPaymentIdPrintRoute: InvoicesPaymentIdPrintRoute,
  RequestsRequestIdPrintRoute: RequestsRequestIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
