/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CustomerRouteRouteImport } from './routes/_customer/route'
import { Route as CustomerDashboardRouteImport } from './routes/_customer/dashboard'
import { Route as CustomerReceiptsRouteImport } from './routes/_customer/receipts'
import { Route as CustomerRequestsRouteImport } from './routes/_customer/requests'
import { Route as WebIndexRouteImport } from './routes/_web/index'
import { Route as WebOnboardingRouteImport } from './routes/_web/onboarding'
import { Route as WebSigninRouteImport } from './routes/_web/signin'
import { Route as WebSignupRouteImport } from './routes/_web/signup'
import { Route as AdminAdminRouteRouteImport } from './routes/admin/_admin/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as AdminAdminIndexRouteImport } from './routes/admin/_admin/index'
import { Route as AdminAdminClientsRouteImport } from './routes/admin/_admin/clients'
import { Route as AdminAdminItemsRouteImport } from './routes/admin/_admin/items'
import { Route as AdminAdminPaymentsRouteImport } from './routes/admin/_admin/payments'
import { Route as AdminAdminRequestsRouteImport } from './routes/admin/_admin/requests'
import { Route as AdminAdminUsersRouteImport } from './routes/admin/_admin/users'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as InvoicesPaymentIdPrintRouteImport } from './routes/invoices/$paymentId/print'
import { Route as RequestsRequestIdPrintRouteImport } from './routes/requests/$requestId/print'
import { Route as AdminInvoicesPaymentIdPrintRouteImport } from './routes/admin/invoices/$paymentId/print'
import { Route as AdminRequestsRequestIdPrintRouteImport } from './routes/admin/requests/$requestId/print'

const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerReceiptsRoute = CustomerReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const WebIndexRoute = WebIndexRouteImport.update({
  id: '/_web/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WebOnboardingRoute = WebOnboardingRouteImport.update({
  id: '/_web/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const WebSigninRoute = WebSigninRouteImport.update({
  id: '/_web/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const WebSignupRoute = WebSignupRouteImport.update({
  id: '/_web/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminRouteRoute = AdminAdminRouteRouteImport.update({
  id: '/admin/_admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminClientsRoute = AdminAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminItemsRoute = AdminAdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminPaymentsRoute = AdminAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminRequestsRoute = AdminAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminAdminRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPaymentIdPrintRoute = InvoicesPaymentIdPrintRouteImport.update({
  id: '/invoices/$paymentId/print',
  path: '/invoices/$paymentId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdPrintRoute = RequestsRequestIdPrintRouteImport.update({
  id: '/requests/$requestId/print',
  path: '/requests/$requestId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminInvoicesPaymentIdPrintRoute =
  AdminInvoicesPaymentIdPrintRouteImport.update({
    id: '/admin/invoices/$paymentId/print',
    path: '/admin/invoices/$paymentId/print',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminRequestsRequestIdPrintRoute =
  AdminRequestsRequestIdPrintRouteImport.update({
    id: '/admin/requests/$requestId/print',
    path: '/admin/requests/$requestId/print',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof WebIndexRoute
  '/admin': typeof AdminAdminRouteRouteWithChildren
  '/dashboard': typeof CustomerDashboardRoute
  '/receipts': typeof CustomerReceiptsRoute
  '/requests': typeof CustomerRequestsRoute
  '/onboarding': typeof WebOnboardingRoute
  '/signin': typeof WebSigninRoute
  '/signup': typeof WebSignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/items': typeof AdminAdminItemsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/invoices/$paymentId/print': typeof AdminInvoicesPaymentIdPrintRoute
  '/admin/requests/$requestId/print': typeof AdminRequestsRequestIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof WebIndexRoute
  '/dashboard': typeof CustomerDashboardRoute
  '/receipts': typeof CustomerReceiptsRoute
  '/requests': typeof CustomerRequestsRoute
  '/onboarding': typeof WebOnboardingRoute
  '/signin': typeof WebSigninRoute
  '/signup': typeof WebSignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/admin/clients': typeof AdminAdminClientsRoute
  '/admin/items': typeof AdminAdminItemsRoute
  '/admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/requests': typeof AdminAdminRequestsRoute
  '/admin/users': typeof AdminAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/invoices/$paymentId/print': typeof AdminInvoicesPaymentIdPrintRoute
  '/admin/requests/$requestId/print': typeof AdminRequestsRequestIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_customer': typeof CustomerRouteRouteWithChildren
  '/admin/_admin': typeof AdminAdminRouteRouteWithChildren
  '/_customer/dashboard': typeof CustomerDashboardRoute
  '/_customer/receipts': typeof CustomerReceiptsRoute
  '/_customer/requests': typeof CustomerRequestsRoute
  '/_web/onboarding': typeof WebOnboardingRoute
  '/_web/signin': typeof WebSigninRoute
  '/_web/signup': typeof WebSignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/$': typeof ApiSplatRoute
  '/_web/': typeof WebIndexRoute
  '/admin/_admin/clients': typeof AdminAdminClientsRoute
  '/admin/_admin/items': typeof AdminAdminItemsRoute
  '/admin/_admin/payments': typeof AdminAdminPaymentsRoute
  '/admin/_admin/requests': typeof AdminAdminRequestsRoute
  '/admin/_admin/users': typeof AdminAdminUsersRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
  '/admin/_admin/': typeof AdminAdminIndexRoute
  '/admin/invoices/$paymentId/print': typeof AdminInvoicesPaymentIdPrintRoute
  '/admin/requests/$requestId/print': typeof AdminRequestsRequestIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/receipts'
    | '/requests'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/api/$'
    | '/admin/clients'
    | '/admin/items'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/users'
    | '/api/auth/$'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
    | '/admin/'
    | '/admin/invoices/$paymentId/print'
    | '/admin/requests/$requestId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/receipts'
    | '/requests'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/admin/login'
    | '/api/$'
    | '/admin/clients'
    | '/admin/items'
    | '/admin/payments'
    | '/admin/requests'
    | '/admin/users'
    | '/api/auth/$'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
    | '/admin'
    | '/admin/invoices/$paymentId/print'
    | '/admin/requests/$requestId/print'
  id:
    | '__root__'
    | '/_customer'
    | '/admin/_admin'
    | '/_customer/dashboard'
    | '/_customer/receipts'
    | '/_customer/requests'
    | '/_web/onboarding'
    | '/_web/signin'
    | '/_web/signup'
    | '/admin/login'
    | '/api/$'
    | '/_web/'
    | '/admin/_admin/clients'
    | '/admin/_admin/items'
    | '/admin/_admin/payments'
    | '/admin/_admin/requests'
    | '/admin/_admin/users'
    | '/api/auth/$'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
    | '/admin/_admin/'
    | '/admin/invoices/$paymentId/print'
    | '/admin/requests/$requestId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  AdminAdminRouteRoute: typeof AdminAdminRouteRouteWithChildren
  WebOnboardingRoute: typeof WebOnboardingRoute
  WebSigninRoute: typeof WebSigninRoute
  WebSignupRoute: typeof WebSignupRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ApiSplatRoute: typeof ApiSplatRoute
  WebIndexRoute: typeof WebIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  InvoicesPaymentIdPrintRoute: typeof InvoicesPaymentIdPrintRoute
  RequestsRequestIdPrintRoute: typeof RequestsRequestIdPrintRoute
  AdminInvoicesPaymentIdPrintRoute: typeof AdminInvoicesPaymentIdPrintRoute
  AdminRequestsRequestIdPrintRoute: typeof AdminRequestsRequestIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/dashboard': {
      id: '/_customer/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/receipts': {
      id: '/_customer/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof CustomerReceiptsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/requests': {
      id: '/_customer/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_web/': {
      id: '/_web/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof WebIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/onboarding': {
      id: '/_web/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof WebOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/signin': {
      id: '/_web/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof WebSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_web/signup': {
      id: '/_web/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof WebSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin': {
      id: '/admin/_admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_admin/': {
      id: '/admin/_admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/clients': {
      id: '/admin/_admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminAdminClientsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/items': {
      id: '/admin/_admin/items'
      path: '/items'
      fullPath: '/admin/items'
      preLoaderRoute: typeof AdminAdminItemsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/payments': {
      id: '/admin/_admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminAdminPaymentsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/requests': {
      id: '/admin/_admin/requests'
      path: '/requests'
      fullPath: '/admin/requests'
      preLoaderRoute: typeof AdminAdminRequestsRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/admin/_admin/users': {
      id: '/admin/_admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminAdminRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$paymentId/print': {
      id: '/invoices/$paymentId/print'
      path: '/invoices/$paymentId/print'
      fullPath: '/invoices/$paymentId/print'
      preLoaderRoute: typeof InvoicesPaymentIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId/print': {
      id: '/requests/$requestId/print'
      path: '/requests/$requestId/print'
      fullPath: '/requests/$requestId/print'
      preLoaderRoute: typeof RequestsRequestIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/invoices/$paymentId/print': {
      id: '/admin/invoices/$paymentId/print'
      path: '/admin/invoices/$paymentId/print'
      fullPath: '/admin/invoices/$paymentId/print'
      preLoaderRoute: typeof AdminInvoicesPaymentIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/requests/$requestId/print': {
      id: '/admin/requests/$requestId/print'
      path: '/admin/requests/$requestId/print'
      fullPath: '/admin/requests/$requestId/print'
      preLoaderRoute: typeof AdminRequestsRequestIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomerRouteRouteChildren {
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerReceiptsRoute: typeof CustomerReceiptsRoute
  CustomerRequestsRoute: typeof CustomerRequestsRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerReceiptsRoute: CustomerReceiptsRoute,
  CustomerRequestsRoute: CustomerRequestsRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

interface AdminAdminRouteRouteChildren {
  AdminAdminClientsRoute: typeof AdminAdminClientsRoute
  AdminAdminItemsRoute: typeof AdminAdminItemsRoute
  AdminAdminPaymentsRoute: typeof AdminAdminPaymentsRoute
  AdminAdminRequestsRoute: typeof AdminAdminRequestsRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminAdminRouteRouteChildren: AdminAdminRouteRouteChildren = {
  AdminAdminClientsRoute: AdminAdminClientsRoute,
  AdminAdminItemsRoute: AdminAdminItemsRoute,
  AdminAdminPaymentsRoute: AdminAdminPaymentsRoute,
  AdminAdminRequestsRoute: AdminAdminRequestsRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminAdminRouteRouteWithChildren = AdminAdminRouteRoute._addFileChildren(
  AdminAdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  AdminAdminRouteRoute: AdminAdminRouteRouteWithChildren,
  WebOnboardingRoute: WebOnboardingRoute,
  WebSigninRoute: WebSigninRoute,
  WebSignupRoute: WebSignupRoute,
  AdminLoginRoute: AdminLoginRoute,
  ApiSplatRoute: ApiSplatRoute,
  WebIndexRoute: WebIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  InvoicesPaymentIdPrintRoute: InvoicesPaymentIdPrintRoute,
  RequestsRequestIdPrintRoute: RequestsRequestIdPrintRoute,
  AdminInvoicesPaymentIdPrintRoute: AdminInvoicesPaymentIdPrintRoute,
  AdminRequestsRequestIdPrintRoute: AdminRequestsRequestIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
