/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SgsAdminAdminRouteRouteImport } from './routes/sgs-admin/_admin/route'
import { Route as SgsAdminLoginRouteImport } from './routes/sgs-admin/login'
import { Route as SgsApiSplatRouteImport } from './routes/sgs-api/$'
import { Route as SgsCustomerRouteRouteImport } from './routes/sgs/_customer/route'
import { Route as SgsAdminAdminIndexRouteImport } from './routes/sgs-admin/_admin/index'
import { Route as SgsAdminAdminClientsRouteImport } from './routes/sgs-admin/_admin/clients'
import { Route as SgsAdminAdminItemsRouteImport } from './routes/sgs-admin/_admin/items'
import { Route as SgsAdminAdminPaymentsRouteImport } from './routes/sgs-admin/_admin/payments'
import { Route as SgsAdminAdminRequestsRouteImport } from './routes/sgs-admin/_admin/requests'
import { Route as SgsAdminAdminUsersRouteImport } from './routes/sgs-admin/_admin/users'
import { Route as SgsCustomerDashboardRouteImport } from './routes/sgs/_customer/dashboard'
import { Route as SgsCustomerReceiptsRouteImport } from './routes/sgs/_customer/receipts'
import { Route as SgsCustomerRequestsRouteImport } from './routes/sgs/_customer/requests'
import { Route as SgsWebIndexRouteImport } from './routes/sgs/_web/index'
import { Route as SgsWebOnboardingRouteImport } from './routes/sgs/_web/onboarding'
import { Route as SgsWebSigninRouteImport } from './routes/sgs/_web/signin'
import { Route as SgsWebSignupRouteImport } from './routes/sgs/_web/signup'
import { Route as SgsAdminInvoicesPaymentIdPrintRouteImport } from './routes/sgs-admin/invoices/$paymentId/print'
import { Route as SgsAdminRequestsRequestIdPrintRouteImport } from './routes/sgs-admin/requests/$requestId/print'
import { Route as SgsApiAuthSplatRouteImport } from './routes/sgs/api/auth/$'
import { Route as SgsInvoicesPaymentIdPrintRouteImport } from './routes/sgs/invoices/$paymentId/print'
import { Route as SgsRequestsRequestIdPrintRouteImport } from './routes/sgs/requests/$requestId/print'

const SgsAdminAdminRouteRoute = SgsAdminAdminRouteRouteImport.update({
  id: '/sgs-admin/_admin',
  path: '/sgs-admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsAdminLoginRoute = SgsAdminLoginRouteImport.update({
  id: '/sgs-admin/login',
  path: '/sgs-admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsApiSplatRoute = SgsApiSplatRouteImport.update({
  id: '/sgs-api/$',
  path: '/sgs-api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsCustomerRouteRoute = SgsCustomerRouteRouteImport.update({
  id: '/sgs/_customer',
  path: '/sgs',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsAdminAdminIndexRoute = SgsAdminAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SgsAdminAdminRouteRoute,
} as any)
const SgsAdminAdminClientsRoute = SgsAdminAdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => SgsAdminAdminRouteRoute,
} as any)
const SgsAdminAdminItemsRoute = SgsAdminAdminItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => SgsAdminAdminRouteRoute,
} as any)
const SgsAdminAdminPaymentsRoute = SgsAdminAdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => SgsAdminAdminRouteRoute,
} as any)
const SgsAdminAdminRequestsRoute = SgsAdminAdminRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => SgsAdminAdminRouteRoute,
} as any)
const SgsAdminAdminUsersRoute = SgsAdminAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => SgsAdminAdminRouteRoute,
} as any)
const SgsCustomerDashboardRoute = SgsCustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => SgsCustomerRouteRoute,
} as any)
const SgsCustomerReceiptsRoute = SgsCustomerReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => SgsCustomerRouteRoute,
} as any)
const SgsCustomerRequestsRoute = SgsCustomerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => SgsCustomerRouteRoute,
} as any)
const SgsWebIndexRoute = SgsWebIndexRouteImport.update({
  id: '/sgs/_web/',
  path: '/sgs/',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsWebOnboardingRoute = SgsWebOnboardingRouteImport.update({
  id: '/sgs/_web/onboarding',
  path: '/sgs/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsWebSigninRoute = SgsWebSigninRouteImport.update({
  id: '/sgs/_web/signin',
  path: '/sgs/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsWebSignupRoute = SgsWebSignupRouteImport.update({
  id: '/sgs/_web/signup',
  path: '/sgs/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsAdminInvoicesPaymentIdPrintRoute =
  SgsAdminInvoicesPaymentIdPrintRouteImport.update({
    id: '/sgs-admin/invoices/$paymentId/print',
    path: '/sgs-admin/invoices/$paymentId/print',
    getParentRoute: () => rootRouteImport,
  } as any)
const SgsAdminRequestsRequestIdPrintRoute =
  SgsAdminRequestsRequestIdPrintRouteImport.update({
    id: '/sgs-admin/requests/$requestId/print',
    path: '/sgs-admin/requests/$requestId/print',
    getParentRoute: () => rootRouteImport,
  } as any)
const SgsApiAuthSplatRoute = SgsApiAuthSplatRouteImport.update({
  id: '/sgs/api/auth/$',
  path: '/sgs/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const SgsInvoicesPaymentIdPrintRoute =
  SgsInvoicesPaymentIdPrintRouteImport.update({
    id: '/sgs/invoices/$paymentId/print',
    path: '/sgs/invoices/$paymentId/print',
    getParentRoute: () => rootRouteImport,
  } as any)
const SgsRequestsRequestIdPrintRoute =
  SgsRequestsRequestIdPrintRouteImport.update({
    id: '/sgs/requests/$requestId/print',
    path: '/sgs/requests/$requestId/print',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/sgs-admin': typeof SgsAdminAdminRouteRouteWithChildren
  '/sgs': typeof SgsCustomerRouteRouteWithChildren
  '/sgs-admin/login': typeof SgsAdminLoginRoute
  '/sgs-api/$': typeof SgsApiSplatRoute
  '/sgs-admin/clients': typeof SgsAdminAdminClientsRoute
  '/sgs-admin/items': typeof SgsAdminAdminItemsRoute
  '/sgs-admin/payments': typeof SgsAdminAdminPaymentsRoute
  '/sgs-admin/requests': typeof SgsAdminAdminRequestsRoute
  '/sgs-admin/users': typeof SgsAdminAdminUsersRoute
  '/sgs/dashboard': typeof SgsCustomerDashboardRoute
  '/sgs/receipts': typeof SgsCustomerReceiptsRoute
  '/sgs/requests': typeof SgsCustomerRequestsRoute
  '/sgs/onboarding': typeof SgsWebOnboardingRoute
  '/sgs/signin': typeof SgsWebSigninRoute
  '/sgs/signup': typeof SgsWebSignupRoute
  '/sgs-admin/': typeof SgsAdminAdminIndexRoute
  '/sgs/': typeof SgsWebIndexRoute
  '/sgs-admin/invoices/$paymentId/print': typeof SgsAdminInvoicesPaymentIdPrintRoute
  '/sgs-admin/requests/$requestId/print': typeof SgsAdminRequestsRequestIdPrintRoute
  '/sgs/api/auth/$': typeof SgsApiAuthSplatRoute
  '/sgs/invoices/$paymentId/print': typeof SgsInvoicesPaymentIdPrintRoute
  '/sgs/requests/$requestId/print': typeof SgsRequestsRequestIdPrintRoute
}
export interface FileRoutesByTo {
  '/sgs': typeof SgsWebIndexRoute
  '/sgs-admin/login': typeof SgsAdminLoginRoute
  '/sgs-api/$': typeof SgsApiSplatRoute
  '/sgs-admin/clients': typeof SgsAdminAdminClientsRoute
  '/sgs-admin/items': typeof SgsAdminAdminItemsRoute
  '/sgs-admin/payments': typeof SgsAdminAdminPaymentsRoute
  '/sgs-admin/requests': typeof SgsAdminAdminRequestsRoute
  '/sgs-admin/users': typeof SgsAdminAdminUsersRoute
  '/sgs/dashboard': typeof SgsCustomerDashboardRoute
  '/sgs/receipts': typeof SgsCustomerReceiptsRoute
  '/sgs/requests': typeof SgsCustomerRequestsRoute
  '/sgs/onboarding': typeof SgsWebOnboardingRoute
  '/sgs/signin': typeof SgsWebSigninRoute
  '/sgs/signup': typeof SgsWebSignupRoute
  '/sgs-admin': typeof SgsAdminAdminIndexRoute
  '/sgs-admin/invoices/$paymentId/print': typeof SgsAdminInvoicesPaymentIdPrintRoute
  '/sgs-admin/requests/$requestId/print': typeof SgsAdminRequestsRequestIdPrintRoute
  '/sgs/api/auth/$': typeof SgsApiAuthSplatRoute
  '/sgs/invoices/$paymentId/print': typeof SgsInvoicesPaymentIdPrintRoute
  '/sgs/requests/$requestId/print': typeof SgsRequestsRequestIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/sgs-admin/_admin': typeof SgsAdminAdminRouteRouteWithChildren
  '/sgs/_customer': typeof SgsCustomerRouteRouteWithChildren
  '/sgs-admin/login': typeof SgsAdminLoginRoute
  '/sgs-api/$': typeof SgsApiSplatRoute
  '/sgs-admin/_admin/clients': typeof SgsAdminAdminClientsRoute
  '/sgs-admin/_admin/items': typeof SgsAdminAdminItemsRoute
  '/sgs-admin/_admin/payments': typeof SgsAdminAdminPaymentsRoute
  '/sgs-admin/_admin/requests': typeof SgsAdminAdminRequestsRoute
  '/sgs-admin/_admin/users': typeof SgsAdminAdminUsersRoute
  '/sgs/_customer/dashboard': typeof SgsCustomerDashboardRoute
  '/sgs/_customer/receipts': typeof SgsCustomerReceiptsRoute
  '/sgs/_customer/requests': typeof SgsCustomerRequestsRoute
  '/sgs/_web/onboarding': typeof SgsWebOnboardingRoute
  '/sgs/_web/signin': typeof SgsWebSigninRoute
  '/sgs/_web/signup': typeof SgsWebSignupRoute
  '/sgs-admin/_admin/': typeof SgsAdminAdminIndexRoute
  '/sgs/_web/': typeof SgsWebIndexRoute
  '/sgs-admin/invoices/$paymentId/print': typeof SgsAdminInvoicesPaymentIdPrintRoute
  '/sgs-admin/requests/$requestId/print': typeof SgsAdminRequestsRequestIdPrintRoute
  '/sgs/api/auth/$': typeof SgsApiAuthSplatRoute
  '/sgs/invoices/$paymentId/print': typeof SgsInvoicesPaymentIdPrintRoute
  '/sgs/requests/$requestId/print': typeof SgsRequestsRequestIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/sgs-admin'
    | '/sgs'
    | '/sgs-admin/login'
    | '/sgs-api/$'
    | '/sgs-admin/clients'
    | '/sgs-admin/items'
    | '/sgs-admin/payments'
    | '/sgs-admin/requests'
    | '/sgs-admin/users'
    | '/sgs/dashboard'
    | '/sgs/receipts'
    | '/sgs/requests'
    | '/sgs/onboarding'
    | '/sgs/signin'
    | '/sgs/signup'
    | '/sgs-admin/'
    | '/sgs/'
    | '/sgs-admin/invoices/$paymentId/print'
    | '/sgs-admin/requests/$requestId/print'
    | '/sgs/api/auth/$'
    | '/sgs/invoices/$paymentId/print'
    | '/sgs/requests/$requestId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/sgs'
    | '/sgs-admin/login'
    | '/sgs-api/$'
    | '/sgs-admin/clients'
    | '/sgs-admin/items'
    | '/sgs-admin/payments'
    | '/sgs-admin/requests'
    | '/sgs-admin/users'
    | '/sgs/dashboard'
    | '/sgs/receipts'
    | '/sgs/requests'
    | '/sgs/onboarding'
    | '/sgs/signin'
    | '/sgs/signup'
    | '/sgs-admin'
    | '/sgs-admin/invoices/$paymentId/print'
    | '/sgs-admin/requests/$requestId/print'
    | '/sgs/api/auth/$'
    | '/sgs/invoices/$paymentId/print'
    | '/sgs/requests/$requestId/print'
  id:
    | '__root__'
    | '/sgs-admin/_admin'
    | '/sgs/_customer'
    | '/sgs-admin/login'
    | '/sgs-api/$'
    | '/sgs-admin/_admin/clients'
    | '/sgs-admin/_admin/items'
    | '/sgs-admin/_admin/payments'
    | '/sgs-admin/_admin/requests'
    | '/sgs-admin/_admin/users'
    | '/sgs/_customer/dashboard'
    | '/sgs/_customer/receipts'
    | '/sgs/_customer/requests'
    | '/sgs/_web/onboarding'
    | '/sgs/_web/signin'
    | '/sgs/_web/signup'
    | '/sgs-admin/_admin/'
    | '/sgs/_web/'
    | '/sgs-admin/invoices/$paymentId/print'
    | '/sgs-admin/requests/$requestId/print'
    | '/sgs/api/auth/$'
    | '/sgs/invoices/$paymentId/print'
    | '/sgs/requests/$requestId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SgsAdminAdminRouteRoute: typeof SgsAdminAdminRouteRouteWithChildren
  SgsCustomerRouteRoute: typeof SgsCustomerRouteRouteWithChildren
  SgsAdminLoginRoute: typeof SgsAdminLoginRoute
  SgsApiSplatRoute: typeof SgsApiSplatRoute
  SgsWebOnboardingRoute: typeof SgsWebOnboardingRoute
  SgsWebSigninRoute: typeof SgsWebSigninRoute
  SgsWebSignupRoute: typeof SgsWebSignupRoute
  SgsWebIndexRoute: typeof SgsWebIndexRoute
  SgsAdminInvoicesPaymentIdPrintRoute: typeof SgsAdminInvoicesPaymentIdPrintRoute
  SgsAdminRequestsRequestIdPrintRoute: typeof SgsAdminRequestsRequestIdPrintRoute
  SgsApiAuthSplatRoute: typeof SgsApiAuthSplatRoute
  SgsInvoicesPaymentIdPrintRoute: typeof SgsInvoicesPaymentIdPrintRoute
  SgsRequestsRequestIdPrintRoute: typeof SgsRequestsRequestIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sgs-admin/_admin': {
      id: '/sgs-admin/_admin'
      path: '/sgs-admin'
      fullPath: '/sgs-admin'
      preLoaderRoute: typeof SgsAdminAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs-admin/login': {
      id: '/sgs-admin/login'
      path: '/sgs-admin/login'
      fullPath: '/sgs-admin/login'
      preLoaderRoute: typeof SgsAdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs-api/$': {
      id: '/sgs-api/$'
      path: '/sgs-api/$'
      fullPath: '/sgs-api/$'
      preLoaderRoute: typeof SgsApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs/_customer': {
      id: '/sgs/_customer'
      path: '/sgs'
      fullPath: '/sgs'
      preLoaderRoute: typeof SgsCustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs-admin/_admin/': {
      id: '/sgs-admin/_admin/'
      path: '/'
      fullPath: '/sgs-admin/'
      preLoaderRoute: typeof SgsAdminAdminIndexRouteImport
      parentRoute: typeof SgsAdminAdminRouteRoute
    }
    '/sgs-admin/_admin/clients': {
      id: '/sgs-admin/_admin/clients'
      path: '/clients'
      fullPath: '/sgs-admin/clients'
      preLoaderRoute: typeof SgsAdminAdminClientsRouteImport
      parentRoute: typeof SgsAdminAdminRouteRoute
    }
    '/sgs-admin/_admin/items': {
      id: '/sgs-admin/_admin/items'
      path: '/items'
      fullPath: '/sgs-admin/items'
      preLoaderRoute: typeof SgsAdminAdminItemsRouteImport
      parentRoute: typeof SgsAdminAdminRouteRoute
    }
    '/sgs-admin/_admin/payments': {
      id: '/sgs-admin/_admin/payments'
      path: '/payments'
      fullPath: '/sgs-admin/payments'
      preLoaderRoute: typeof SgsAdminAdminPaymentsRouteImport
      parentRoute: typeof SgsAdminAdminRouteRoute
    }
    '/sgs-admin/_admin/requests': {
      id: '/sgs-admin/_admin/requests'
      path: '/requests'
      fullPath: '/sgs-admin/requests'
      preLoaderRoute: typeof SgsAdminAdminRequestsRouteImport
      parentRoute: typeof SgsAdminAdminRouteRoute
    }
    '/sgs-admin/_admin/users': {
      id: '/sgs-admin/_admin/users'
      path: '/users'
      fullPath: '/sgs-admin/users'
      preLoaderRoute: typeof SgsAdminAdminUsersRouteImport
      parentRoute: typeof SgsAdminAdminRouteRoute
    }
    '/sgs/_customer/dashboard': {
      id: '/sgs/_customer/dashboard'
      path: '/dashboard'
      fullPath: '/sgs/dashboard'
      preLoaderRoute: typeof SgsCustomerDashboardRouteImport
      parentRoute: typeof SgsCustomerRouteRoute
    }
    '/sgs/_customer/receipts': {
      id: '/sgs/_customer/receipts'
      path: '/receipts'
      fullPath: '/sgs/receipts'
      preLoaderRoute: typeof SgsCustomerReceiptsRouteImport
      parentRoute: typeof SgsCustomerRouteRoute
    }
    '/sgs/_customer/requests': {
      id: '/sgs/_customer/requests'
      path: '/requests'
      fullPath: '/sgs/requests'
      preLoaderRoute: typeof SgsCustomerRequestsRouteImport
      parentRoute: typeof SgsCustomerRouteRoute
    }
    '/sgs/_web/': {
      id: '/sgs/_web/'
      path: '/sgs'
      fullPath: '/sgs/'
      preLoaderRoute: typeof SgsWebIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs/_web/onboarding': {
      id: '/sgs/_web/onboarding'
      path: '/sgs/onboarding'
      fullPath: '/sgs/onboarding'
      preLoaderRoute: typeof SgsWebOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs/_web/signin': {
      id: '/sgs/_web/signin'
      path: '/sgs/signin'
      fullPath: '/sgs/signin'
      preLoaderRoute: typeof SgsWebSigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs/_web/signup': {
      id: '/sgs/_web/signup'
      path: '/sgs/signup'
      fullPath: '/sgs/signup'
      preLoaderRoute: typeof SgsWebSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs-admin/invoices/$paymentId/print': {
      id: '/sgs-admin/invoices/$paymentId/print'
      path: '/sgs-admin/invoices/$paymentId/print'
      fullPath: '/sgs-admin/invoices/$paymentId/print'
      preLoaderRoute: typeof SgsAdminInvoicesPaymentIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs-admin/requests/$requestId/print': {
      id: '/sgs-admin/requests/$requestId/print'
      path: '/sgs-admin/requests/$requestId/print'
      fullPath: '/sgs-admin/requests/$requestId/print'
      preLoaderRoute: typeof SgsAdminRequestsRequestIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs/api/auth/$': {
      id: '/sgs/api/auth/$'
      path: '/sgs/api/auth/$'
      fullPath: '/sgs/api/auth/$'
      preLoaderRoute: typeof SgsApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs/invoices/$paymentId/print': {
      id: '/sgs/invoices/$paymentId/print'
      path: '/sgs/invoices/$paymentId/print'
      fullPath: '/sgs/invoices/$paymentId/print'
      preLoaderRoute: typeof SgsInvoicesPaymentIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sgs/requests/$requestId/print': {
      id: '/sgs/requests/$requestId/print'
      path: '/sgs/requests/$requestId/print'
      fullPath: '/sgs/requests/$requestId/print'
      preLoaderRoute: typeof SgsRequestsRequestIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SgsAdminAdminRouteRouteChildren {
  SgsAdminAdminClientsRoute: typeof SgsAdminAdminClientsRoute
  SgsAdminAdminItemsRoute: typeof SgsAdminAdminItemsRoute
  SgsAdminAdminPaymentsRoute: typeof SgsAdminAdminPaymentsRoute
  SgsAdminAdminRequestsRoute: typeof SgsAdminAdminRequestsRoute
  SgsAdminAdminUsersRoute: typeof SgsAdminAdminUsersRoute
  SgsAdminAdminIndexRoute: typeof SgsAdminAdminIndexRoute
}

const SgsAdminAdminRouteRouteChildren: SgsAdminAdminRouteRouteChildren = {
  SgsAdminAdminClientsRoute: SgsAdminAdminClientsRoute,
  SgsAdminAdminItemsRoute: SgsAdminAdminItemsRoute,
  SgsAdminAdminPaymentsRoute: SgsAdminAdminPaymentsRoute,
  SgsAdminAdminRequestsRoute: SgsAdminAdminRequestsRoute,
  SgsAdminAdminUsersRoute: SgsAdminAdminUsersRoute,
  SgsAdminAdminIndexRoute: SgsAdminAdminIndexRoute,
}

const SgsAdminAdminRouteRouteWithChildren =
  SgsAdminAdminRouteRoute._addFileChildren(SgsAdminAdminRouteRouteChildren)

interface SgsCustomerRouteRouteChildren {
  SgsCustomerDashboardRoute: typeof SgsCustomerDashboardRoute
  SgsCustomerReceiptsRoute: typeof SgsCustomerReceiptsRoute
  SgsCustomerRequestsRoute: typeof SgsCustomerRequestsRoute
}

const SgsCustomerRouteRouteChildren: SgsCustomerRouteRouteChildren = {
  SgsCustomerDashboardRoute: SgsCustomerDashboardRoute,
  SgsCustomerReceiptsRoute: SgsCustomerReceiptsRoute,
  SgsCustomerRequestsRoute: SgsCustomerRequestsRoute,
}

const SgsCustomerRouteRouteWithChildren =
  SgsCustomerRouteRoute._addFileChildren(SgsCustomerRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SgsAdminAdminRouteRoute: SgsAdminAdminRouteRouteWithChildren,
  SgsCustomerRouteRoute: SgsCustomerRouteRouteWithChildren,
  SgsAdminLoginRoute: SgsAdminLoginRoute,
  SgsApiSplatRoute: SgsApiSplatRoute,
  SgsWebOnboardingRoute: SgsWebOnboardingRoute,
  SgsWebSigninRoute: SgsWebSigninRoute,
  SgsWebSignupRoute: SgsWebSignupRoute,
  SgsWebIndexRoute: SgsWebIndexRoute,
  SgsAdminInvoicesPaymentIdPrintRoute: SgsAdminInvoicesPaymentIdPrintRoute,
  SgsAdminRequestsRequestIdPrintRoute: SgsAdminRequestsRequestIdPrintRoute,
  SgsApiAuthSplatRoute: SgsApiAuthSplatRoute,
  SgsInvoicesPaymentIdPrintRoute: SgsInvoicesPaymentIdPrintRoute,
  SgsRequestsRequestIdPrintRoute: SgsRequestsRequestIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
