/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CustomerRouteRouteImport } from './routes/_customer/route'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as CustomerDashboardRouteImport } from './routes/_customer/dashboard'
import { Route as CustomerReceiptsRouteImport } from './routes/_customer/receipts'
import { Route as CustomerRequestsRouteImport } from './routes/_customer/requests'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as InvoicesPaymentIdPrintRouteImport } from './routes/invoices/$paymentId/print'
import { Route as RequestsRequestIdPrintRouteImport } from './routes/requests/$requestId/print'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerRouteRoute = CustomerRouteRouteImport.update({
  id: '/_customer',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerDashboardRoute = CustomerDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerReceiptsRoute = CustomerReceiptsRouteImport.update({
  id: '/receipts',
  path: '/receipts',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const CustomerRequestsRoute = CustomerRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => CustomerRouteRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesPaymentIdPrintRoute = InvoicesPaymentIdPrintRouteImport.update({
  id: '/invoices/$paymentId/print',
  path: '/invoices/$paymentId/print',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestsRequestIdPrintRoute = RequestsRequestIdPrintRouteImport.update({
  id: '/requests/$requestId/print',
  path: '/requests/$requestId/print',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof CustomerDashboardRoute
  '/receipts': typeof CustomerReceiptsRoute
  '/requests': typeof CustomerRequestsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof CustomerDashboardRoute
  '/receipts': typeof CustomerReceiptsRoute
  '/requests': typeof CustomerRequestsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_customer': typeof CustomerRouteRouteWithChildren
  '/onboarding': typeof OnboardingRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
  '/_customer/dashboard': typeof CustomerDashboardRoute
  '/_customer/receipts': typeof CustomerReceiptsRoute
  '/_customer/requests': typeof CustomerRequestsRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/invoices/$paymentId/print': typeof InvoicesPaymentIdPrintRoute
  '/requests/$requestId/print': typeof RequestsRequestIdPrintRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/receipts'
    | '/requests'
    | '/api/auth/$'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/dashboard'
    | '/receipts'
    | '/requests'
    | '/api/auth/$'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
  id:
    | '__root__'
    | '/'
    | '/_customer'
    | '/onboarding'
    | '/signin'
    | '/signup'
    | '/_customer/dashboard'
    | '/_customer/receipts'
    | '/_customer/requests'
    | '/api/auth/$'
    | '/invoices/$paymentId/print'
    | '/requests/$requestId/print'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomerRouteRoute: typeof CustomerRouteRouteWithChildren
  OnboardingRoute: typeof OnboardingRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  InvoicesPaymentIdPrintRoute: typeof InvoicesPaymentIdPrintRoute
  RequestsRequestIdPrintRoute: typeof RequestsRequestIdPrintRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer': {
      id: '/_customer'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof CustomerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_customer/dashboard': {
      id: '/_customer/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof CustomerDashboardRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/receipts': {
      id: '/_customer/receipts'
      path: '/receipts'
      fullPath: '/receipts'
      preLoaderRoute: typeof CustomerReceiptsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/_customer/requests': {
      id: '/_customer/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof CustomerRequestsRouteImport
      parentRoute: typeof CustomerRouteRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/$paymentId/print': {
      id: '/invoices/$paymentId/print'
      path: '/invoices/$paymentId/print'
      fullPath: '/invoices/$paymentId/print'
      preLoaderRoute: typeof InvoicesPaymentIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requests/$requestId/print': {
      id: '/requests/$requestId/print'
      path: '/requests/$requestId/print'
      fullPath: '/requests/$requestId/print'
      preLoaderRoute: typeof RequestsRequestIdPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CustomerRouteRouteChildren {
  CustomerDashboardRoute: typeof CustomerDashboardRoute
  CustomerReceiptsRoute: typeof CustomerReceiptsRoute
  CustomerRequestsRoute: typeof CustomerRequestsRoute
}

const CustomerRouteRouteChildren: CustomerRouteRouteChildren = {
  CustomerDashboardRoute: CustomerDashboardRoute,
  CustomerReceiptsRoute: CustomerReceiptsRoute,
  CustomerRequestsRoute: CustomerRequestsRoute,
}

const CustomerRouteRouteWithChildren = CustomerRouteRoute._addFileChildren(
  CustomerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomerRouteRoute: CustomerRouteRouteWithChildren,
  OnboardingRoute: OnboardingRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  InvoicesPaymentIdPrintRoute: InvoicesPaymentIdPrintRoute,
  RequestsRequestIdPrintRoute: RequestsRequestIdPrintRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
